spring:
  datasource:
    data-username: root
    data-password: root
  cloud:
    
    gcp:
      project-id: steve-7da8a   
      sql:
        database-name: laundry
        instance-connection-name: steve-7da8a:australia-southeast1:laundrydb
        
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 9090