spring:
  cloud:
    gcp:
      config:
        project-id: steve-7da8a
      sql:
        database-name: laundry
        instance-connection-name: steve-7da8a:australia-southeast1:laundrydb
        userName: root
        password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 9090