spring:
  profiles:
    active:
    - dev
  main:
    allow-bean-definition-overriding: true

---

spring:

  datasource:
    url: jdbc:mysql://steve-7da8a:australia-southeast1:laundrydb:3306/laundry?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mysql.sys
    password: root
    naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 9090
  
  
---

spring:
  profiles: uat
  orddatasource:
    jdbc-url: jdbc:mariadb://crmdev01.cxdnunmy8ldc.ap-southeast-1.rds.amazonaws.com/crmquote?useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: crmquote_appl
    password: crmquote_appl
  eavdatasource:
    jdbc-url: jdbc:mariadb://crmdev01.cxdnunmy8ldc.ap-southeast-1.rds.amazonaws.com/crmeav?useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: crmquote_appl
    password: crmquote_appl
  jpa.hibernate:
    ddl-auto: none
    show-sql: true
    naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 9090
        